// Code generated by Fern. DO NOT EDIT.

package orpcapi

import (
	json "encoding/json"
	core "github.com/joeblew999/orpc-api/sdk/go/core"
)

// Unprocessable Entity
type UnprocessableEntityError struct {
	*core.APIError
	Body *ErrorModel
}

func (u *UnprocessableEntityError) UnmarshalJSON(data []byte) error {
	var body *ErrorModel
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 422
	u.Body = body
	return nil
}

func (u *UnprocessableEntityError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnprocessableEntityError) Unwrap() error {
	return u.APIError
}

func (u *UnprocessableEntityError) GetBody() *ErrorModel {
	if u == nil {
		return nil
	}
	return u.Body
}
