// Code generated by Fern. DO NOT EDIT.

package meta

import (
	context "context"
	os "os"

	notes "github.com/joeblew999/charter/examples/notes-go/sdk/go"
	core "github.com/joeblew999/charter/examples/notes-go/sdk/go/core"
	internal "github.com/joeblew999/charter/examples/notes-go/sdk/go/internal"
	option "github.com/joeblew999/charter/examples/notes-go/sdk/go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.AccessClientID == "" {
		options.AccessClientID = os.Getenv("CHARTER_NOTES_GO_ACCESS_CLIENT_ID")
	}
	if options.AccessClientSecret == "" {
		options.AccessClientSecret = os.Getenv("CHARTER_NOTES_GO_ACCESS_CLIENT_SECRET")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	client.Meta.Hello(
//	    context.TODO(),
//	)
func (c *Client) Hello(
	ctx context.Context,
	opts ...option.RequestOption,
) (*notes.HelloOutputBody, error) {
	response, err := c.WithRawResponse.Hello(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
