// Code generated by Fern. DO NOT EDIT.

package notes

import (
	core "github.com/joeblew999/charter/examples/notes-go/sdk/go/core"
	internal "github.com/joeblew999/charter/examples/notes-go/sdk/go/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
	422: func(apiError *core.APIError) error {
		return &UnprocessableEntityError{
			APIError: apiError,
		}
	},
	401: func(apiError *core.APIError) error {
		return &UnauthorizedError{
			APIError: apiError,
		}
	},
}
