// Code generated by Fern. DO NOT EDIT.

package notes

import (
	json "encoding/json"
	core "github.com/joeblew999/charter/examples/notes-go/sdk/go/core"
)

// Too Many Requests: more than 100 calls in 60 s by this caller
type TooManyRequestsError struct {
	*core.APIError
	Body *ErrorModel
}

func (t *TooManyRequestsError) UnmarshalJSON(data []byte) error {
	var body *ErrorModel
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	t.StatusCode = 429
	t.Body = body
	return nil
}

func (t *TooManyRequestsError) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.Body)
}

func (t *TooManyRequestsError) Unwrap() error {
	return t.APIError
}

func (t *TooManyRequestsError) GetBody() *ErrorModel {
	if t == nil {
		return nil
	}
	return t.Body
}

// Unauthorized
type UnauthorizedError struct {
	*core.APIError
	Body *ErrorModel
}

func (u *UnauthorizedError) UnmarshalJSON(data []byte) error {
	var body *ErrorModel
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 401
	u.Body = body
	return nil
}

func (u *UnauthorizedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnauthorizedError) Unwrap() error {
	return u.APIError
}

func (u *UnauthorizedError) GetBody() *ErrorModel {
	if u == nil {
		return nil
	}
	return u.Body
}

// Unprocessable Entity
type UnprocessableEntityError struct {
	*core.APIError
	Body *ErrorModel
}

func (u *UnprocessableEntityError) UnmarshalJSON(data []byte) error {
	var body *ErrorModel
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 422
	u.Body = body
	return nil
}

func (u *UnprocessableEntityError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnprocessableEntityError) Unwrap() error {
	return u.APIError
}

func (u *UnprocessableEntityError) GetBody() *ErrorModel {
	if u == nil {
		return nil
	}
	return u.Body
}
