// Code generated by Fern. DO NOT EDIT.

package orpcapi

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/joeblew999/charter/examples/notes-go/sdk/go/internal"
	big "math/big"
)

var (
	createInputBodyFieldBody = big.NewInt(1 << 0)
)

type CreateInputBody struct {
	Body string `json:"body" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateInputBody) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetBody sets the Body field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateInputBody) SetBody(body string) {
	c.Body = body
	c.require(createInputBodyFieldBody)
}

func (c *CreateInputBody) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateInputBody
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateInputBody(body)
	return nil
}

func (c *CreateInputBody) MarshalJSON() ([]byte, error) {
	type embed CreateInputBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	listNotesRequestFieldCursor = big.NewInt(1 << 0)
	listNotesRequestFieldLimit  = big.NewInt(1 << 1)
)

type ListNotesRequest struct {
	// Opaque cursor from the previous page's next_cursor
	Cursor *string `json:"-" url:"cursor,omitempty"`
	Limit  *int    `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListNotesRequest) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListNotesRequest) SetCursor(cursor *string) {
	l.Cursor = cursor
	l.require(listNotesRequestFieldCursor)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListNotesRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listNotesRequestFieldLimit)
}

var (
	listOutputBodyFieldData       = big.NewInt(1 << 0)
	listOutputBodyFieldNextCursor = big.NewInt(1 << 1)
)

type ListOutputBody struct {
	Data []*Note `json:"data" url:"data"`
	// Pass as cursor for the next page; absent on the last page
	NextCursor *string `json:"next_cursor,omitempty" url:"next_cursor,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListOutputBody) GetData() []*Note {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListOutputBody) GetNextCursor() *string {
	if l == nil {
		return nil
	}
	return l.NextCursor
}

func (l *ListOutputBody) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListOutputBody) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListOutputBody) SetData(data []*Note) {
	l.Data = data
	l.require(listOutputBodyFieldData)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListOutputBody) SetNextCursor(nextCursor *string) {
	l.NextCursor = nextCursor
	l.require(listOutputBodyFieldNextCursor)
}

func (l *ListOutputBody) UnmarshalJSON(data []byte) error {
	type unmarshaler ListOutputBody
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListOutputBody(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListOutputBody) MarshalJSON() ([]byte, error) {
	type embed ListOutputBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListOutputBody) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	noteFieldBody      = big.NewInt(1 << 0)
	noteFieldCreatedAt = big.NewInt(1 << 1)
	noteFieldID        = big.NewInt(1 << 2)
)

type Note struct {
	Body      string `json:"body" url:"body"`
	CreatedAt string `json:"created_at" url:"created_at"`
	ID        int64  `json:"id" url:"id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *Note) GetBody() string {
	if n == nil {
		return ""
	}
	return n.Body
}

func (n *Note) GetCreatedAt() string {
	if n == nil {
		return ""
	}
	return n.CreatedAt
}

func (n *Note) GetID() int64 {
	if n == nil {
		return 0
	}
	return n.ID
}

func (n *Note) GetExtraProperties() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.extraProperties
}

func (n *Note) require(field *big.Int) {
	next := new(big.Int)
	if n.explicitFields != nil {
		next.Set(n.explicitFields)
	}
	next.Or(next, field)
	n.explicitFields = next
}

// SetBody sets the Body field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *Note) SetBody(body string) {
	n.Body = body
	n.require(noteFieldBody)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *Note) SetCreatedAt(createdAt string) {
	n.CreatedAt = createdAt
	n.require(noteFieldCreatedAt)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *Note) SetID(id int64) {
	n.ID = id
	n.require(noteFieldID)
}

func (n *Note) UnmarshalJSON(data []byte) error {
	type unmarshaler Note
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = Note(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *Note) MarshalJSON() ([]byte, error) {
	type embed Note
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *Note) String() string {
	if n == nil {
		return "<nil>"
	}
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

var (
	watchNotesRequestFieldAfter   = big.NewInt(1 << 0)
	watchNotesRequestFieldSeconds = big.NewInt(1 << 1)
)

type WatchNotesRequest struct {
	// Resume after this note id (the id of the last note you received). Absent: only notes created from now on
	After *string `json:"-" url:"after,omitempty"`
	// How long to keep the stream open
	Seconds *int `json:"-" url:"seconds,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (w *WatchNotesRequest) require(field *big.Int) {
	next := new(big.Int)
	if w.explicitFields != nil {
		next.Set(w.explicitFields)
	}
	next.Or(next, field)
	w.explicitFields = next
}

// SetAfter sets the After field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WatchNotesRequest) SetAfter(after *string) {
	w.After = after
	w.require(watchNotesRequestFieldAfter)
}

// SetSeconds sets the Seconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WatchNotesRequest) SetSeconds(seconds *int) {
	w.Seconds = seconds
	w.require(watchNotesRequestFieldSeconds)
}
