// Code generated by gsx; DO NOT EDIT.

package pages

import (
	"strconv"

	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	"github.com/joeblew999/charter/examples/start-datastar/api"
	_gsxio "io"
)

//line home.gsx:11:1
// Home is the page at /: the form, and the newest messages, newest first. The list follows the
// stream from the newest message it shows (after): Datastar's @get opens it when the list appears
// (data-init), and each datastar-patch-elements event puts its message at the top of the list.
// retry 'always' connects again when a stream ends, with the id of the last event it had
// (Last-Event-ID), so no message is lost or shown twice.

//line home.gsx:16:1
func Home(messages []api.Message, after int64) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line home.gsx:17:2
		_gsxgw.NodeResult(_gsxrenderLayout(ctx, _gsxgw, "charter-start-datastar", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line home.gsx:18:3
			_gsxgw.S("<h1>Messages</h1>")
//line home.gsx:19:3
			_gsxgw.S("<p>Post one, and it shows at once on every page open here.</p>")
//line home.gsx:20:3
			_gsxgw.NodeResult(_gsxrenderForm(ctx, _gsxgw, "", ""))
//line home.gsx:21:3
			_gsxgw.S("<ul id=\"messages\" data-init=\"")
			_gsxgw.AttrValue(string(follows(after)))
			_gsxgw.S("\">")
//line home.gsx:22:4
			for _, message := range messages {
//line home.gsx:23:5
				_gsxgw.NodeResult(_gsxrenderItem(ctx, _gsxgw, message))
			}
			_gsxgw.S("</ul>")
			return _gsxgw.Err()
		})))
		return _gsxgw.Err()
	})
}

// follows is the list's data-init. gsx cannot check a hole in a Datastar expression (an action
// starts with @, which is not JavaScript), so it is built here, from a number and nothing else.
//
//line home.gsx:29:1
func follows(after int64) gsx.RawJS {
	return gsx.RawJS("@get('/messages/stream?after=" + strconv.FormatInt(after, 10) + "', {retry: 'always'})")
}

// Form is the form, and what POST /messages answers: Datastar puts it in place of the one sent (its
// id, and the Datastar-Mode header: replace), empty, or with what was typed and why it was refused.

//line home.gsx:37:1
func Form(body string, problem string) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderForm(ctx, _gsxgw, body, problem)
	})
}

func _gsxrenderForm(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, body string, problem string) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line home.gsx:38:2
	_gsxgw.S("<form id=\"post\" data-on:submit=\"@post(&#39;/messages&#39;, {contentType: &#39;form&#39;})\">")
//line home.gsx:39:3
	_gsxgw.S("<input name=\"body\" value=\"")
	_gsxgw.AttrValue(string(body))
	_gsxgw.S("\" maxlength=\"")
	_gsxgw.AttrValue(string(strconv.Itoa(api.MaxBody)))
	_gsxgw.S("\"")
	_gsxgw.BoolAttr("required", true)
	_gsxgw.BoolAttr("autofocus", true)
	_gsxgw.S(" autocomplete=\"off\" placeholder=\"Say something\" aria-label=\"Message\">")
//line home.gsx:49:3
	_gsxgw.S("<button type=\"submit\">Post</button>")
//line home.gsx:50:3
	if problem != "" {
//line home.gsx:51:4
		_gsxgw.S("<p class=\"problem\">")
//line home.gsx:51:23
		_gsxgw.Text(string(problem))
		_gsxgw.S("</p>")
	}
	_gsxgw.S("</form>")
	return _gsxgw.Err()
}

//line home.gsx:56:1
// Item is one message: in the list, and what the stream sends of each new one.

//line home.gsx:57:1
func Item(message api.Message) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderItem(ctx, _gsxgw, message)
	})
}

func _gsxrenderItem(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, message api.Message) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line home.gsx:58:2
	_gsxgw.S("<li id=\"")
	_gsxgw.AttrValue(string("message-" + strconv.FormatInt(message.ID, 10)))
	_gsxgw.S("\">")
//line home.gsx:59:3
	_gsxgw.S("<span>")
//line home.gsx:59:9
	_gsxgw.Text(string(message.Body))
	_gsxgw.S("</span>")
//line home.gsx:60:3
	_gsxgw.S("<time>")
//line home.gsx:60:9
	_gsxgw.Text(string(message.CreatedAt))
	_gsxgw.S("</time></li>")
	return _gsxgw.Err()
}
