// Code generated by gsx; DO NOT EDIT.

package pages

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxio "io"
)

//line layout.gsx:5:1
// Layout is the document around every page. Datastar comes from this Worker (/static/), as does the
// stylesheet: no other site is asked for anything.

//line layout.gsx:7:1
func Layout(title string, children gsx.Node) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderLayout(ctx, _gsxgw, title, children)
	})
}

func _gsxrenderLayout(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, title string, children gsx.Node) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
	_gsxgw.S("<!DOCTYPE html>")
//line layout.gsx:9:2
	_gsxgw.S("<html lang=\"en\">")
//line layout.gsx:10:3
	_gsxgw.S("<head>")
//line layout.gsx:11:4
	_gsxgw.S("<meta charset=\"utf-8\">")
//line layout.gsx:12:4
	_gsxgw.S("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">")
//line layout.gsx:13:4
	_gsxgw.S("<title>")
//line layout.gsx:13:11
	_gsxgw.Text(string(title))
	_gsxgw.S("</title>")
//line layout.gsx:14:4
	_gsxgw.S("<link rel=\"stylesheet\" href=\"/static/site.css\"")
	_gsxgw.Nonce(ctx)
	_gsxgw.S(">")
//line layout.gsx:15:4
	_gsxgw.S("<script type=\"module\" src=\"/static/datastar-1.0.4.js\"")
	_gsxgw.Nonce(ctx)
	_gsxgw.S("></script></head>")
//line layout.gsx:17:3
	_gsxgw.S("<body>")
//line layout.gsx:18:4
	_gsxgw.S("<main>")
//line layout.gsx:18:10
	_gsxgw.Node(ctx, children)
	_gsxgw.S("</main></body></html>")
	return _gsxgw.Err()
}
