// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/joeblew999/orpc-api/sdk/go/core"
	internal "github.com/joeblew999/orpc-api/sdk/go/internal"
	meta "github.com/joeblew999/orpc-api/sdk/go/meta"
	notes "github.com/joeblew999/orpc-api/sdk/go/notes"
	option "github.com/joeblew999/orpc-api/sdk/go/option"
)

type Client struct {
	Meta  *meta.Client
	Notes *notes.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Meta:    meta.NewClient(options),
		Notes:   notes.NewClient(options),
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
