// Code generated by gsx; DO NOT EDIT.

package pages

import (
	"strconv"

	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	"github.com/joeblew999/charter/examples/start-htmx/api"
	_gsxio "io"
)

//line home.gsx:9:1
// Home is the page at /: the form, and the newest messages, newest first. The list follows the
// stream from the newest message it shows (after): htmx 4's SSE extension (hx-sse:connect) puts the
// HTML of each event at the top of the list (hx-swap), and when it connects again it sends the id
// of the last event it had, so no message is lost or shown twice.

//line home.gsx:13:1
func Home(messages []api.Message, after int64) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line home.gsx:14:2
		_gsxgw.NodeResult(_gsxrenderLayout(ctx, _gsxgw, "charter-start-htmx", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line home.gsx:15:3
			_gsxgw.S("<h1>Messages</h1>")
//line home.gsx:16:3
			_gsxgw.S("<p>Post one, and it shows at once on every page open here.</p>")
//line home.gsx:17:3
			_gsxgw.NodeResult(_gsxrenderForm(ctx, _gsxgw, "", ""))
//line home.gsx:18:3
			_gsxgw.S("<ul id=\"messages\" hx-sse:connect=\"")
			_gsxgw.URL(string("/messages/stream?after=" + strconv.FormatInt(after, 10)))
			_gsxgw.S("\" hx-swap=\"afterbegin\">")
//line home.gsx:23:4
			for _, message := range messages {
//line home.gsx:24:5
				_gsxgw.NodeResult(_gsxrenderItem(ctx, _gsxgw, message))
			}
			_gsxgw.S("</ul>")
			return _gsxgw.Err()
		})))
		return _gsxgw.Err()
	})
}

//line home.gsx:30:1
// Form is the form, and what POST /messages answers: htmx puts it in place of the one sent
// (outerHTML), empty, or with what was typed and why it was refused.

//line home.gsx:32:1
func Form(body string, problem string) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderForm(ctx, _gsxgw, body, problem)
	})
}

func _gsxrenderForm(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, body string, problem string) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line home.gsx:33:2
	_gsxgw.S("<form id=\"post\" hx-post=\"/messages\" hx-swap=\"outerHTML\">")
//line home.gsx:34:3
	_gsxgw.S("<input name=\"body\" value=\"")
	_gsxgw.AttrValue(string(body))
	_gsxgw.S("\" maxlength=\"")
	_gsxgw.AttrValue(string(strconv.Itoa(api.MaxBody)))
	_gsxgw.S("\"")
	_gsxgw.BoolAttr("required", true)
	_gsxgw.BoolAttr("autofocus", true)
	_gsxgw.S(" autocomplete=\"off\" placeholder=\"Say something\" aria-label=\"Message\">")
//line home.gsx:44:3
	_gsxgw.S("<button type=\"submit\">Post</button>")
//line home.gsx:45:3
	if problem != "" {
//line home.gsx:46:4
		_gsxgw.S("<p class=\"problem\">")
//line home.gsx:46:23
		_gsxgw.Text(string(problem))
		_gsxgw.S("</p>")
	}
	_gsxgw.S("</form>")
	return _gsxgw.Err()
}

//line home.gsx:51:1
// Item is one message: in the list, and what the stream sends of each new one.

//line home.gsx:52:1
func Item(message api.Message) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderItem(ctx, _gsxgw, message)
	})
}

func _gsxrenderItem(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, message api.Message) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line home.gsx:53:2
	_gsxgw.S("<li id=\"")
	_gsxgw.AttrValue(string("message-" + strconv.FormatInt(message.ID, 10)))
	_gsxgw.S("\">")
//line home.gsx:54:3
	_gsxgw.S("<span>")
//line home.gsx:54:9
	_gsxgw.Text(string(message.Body))
	_gsxgw.S("</span>")
//line home.gsx:55:3
	_gsxgw.S("<time>")
//line home.gsx:55:9
	_gsxgw.Text(string(message.CreatedAt))
	_gsxgw.S("</time></li>")
	return _gsxgw.Err()
}
